### ISSUE TITLE
Push repo upstream

### ISSUE THREAD

**Issue by rmzelle** [inukshuk/Sheldon#17]
@inukshuk, would it be possible to push this project upstream and start running things based off citation-style-language/Sheldon?

**Comment by inukshuk** [comment]
Yes, we'll just have to update the continuous deployment credentials. Do you have the `travis` command line tool installed?

**Comment by rmzelle** [comment]
Not yet.

**Comment by inukshuk** [comment]
I'll open a PR.

We will then have to setup Travis for deploying to Heroku. Basically, this entails encrypting the Heroku auth token using your Travis credentials. The end result is [this line](https://github.com/inukshuk/Sheldon/blob/master/.travis.yml#L16) (see [here](http://docs.travis-ci.com/user/deployment/heroku/) for full explanation).

**Comment by rmzelle** [comment]
So if I update that api key, Travis CI will deploy via my own Heroku account? Not that that would be a problem, just trying to figure out how this works.

And should we change the name of the heroku app (away from "shelbot"), or wouldn't there be a name conflict (since shelbot.herokuapp.com already exists)?

**Comment by inukshuk** [comment]
I was rather hoping of keeping the existing Heroku deployment (unless you want to be the owner of the account). We just need to change the encryption of the key so that it can be decrypted using your Travis credentials. If you have `travis` installed, you should be able to run `travis encrypt $(heroku auth:token) --add deploy.api_key` to update the key in `travis.yml`.

Now, this command assumes that you have `heroku` installed as well and that you have access to the auth token as a collaborator -- I'm actually not sure that this works. So to make it easier, I'll have to securely send you the token then you can run  `travis encrypt TOKEN  --add deploy.api_key`.

So, step by step:
1. Merge my PR
2. Enable Travis CI for the repository
3. Update `travis.yml` with the key encrypted using your credentials
4. Change the version in `lib/sheldon/version.rb` to `0.0.1` (without the alpha)
5. Commit changes
6. Push
7. Check travis
8. If the build is green, check https://shelbot.herokuapp.com/version -- if the deployment succeeded it should show the new version.

**Comment by inukshuk** [comment]
If you do want to be the owner of the Herkou account, I'll just transfer ownership to you and you can add me as a collaborator. I'm just not sure what rights collaborators have (i.e. can they check log files etc., so I'd rather stay on as account owner).

**Comment by rmzelle** [comment]
Great, thanks for the detailed instructions. I think I got it all up and running (https://shelbot.herokuapp.com/version shows "1.0.0"). I just had to make one additional change: https://github.com/citation-style-language/Sheldon/commit/a66b79dd2004dd36ee499647ad87c38e63120a56

It's probably easier to keep you as owner of the Heroku account. I'll also give you commit rights to the CSL Sheldon repo.

**Comment by inukshuk** [comment]
Awesome, good work!
